---
title: "STAT 345 Final"
author: "Amber Duevel"
date: "4/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r dice}
dice<-function(verbose=FALSE){
  face <- sample(1:6, 2, replace=TRUE)
  if(face[1]==face[2]){
    double = TRUE
    return("Rolled:", face[1], face[2])
    else
    double=FALSE
    return("Rolled:", face[1], face[2])
    movement = sum(face)
  }
}

dice_simple<- function(verbose= FALSE){
  face<- sample(1:6, 2, replace=TRUE)
  movement=sum(face)
}
```

```{r game board}
library(dplyr)

gameboard<- data.frame(space=1:40, title= c("Go" , "Mediterranean Avenue" , "Community Chest" , "Baltic Avenue" , "Income Tax" , "Reading Railroad" , "Oriental Avenue" , "Chance" , "Vermont Avenue" , "Connecticut Avenue" , "Jail" , "St. Charles Place" , "Electric Company" , "States Avenue" , "Virginia Avenue" , "Pennsylvania Railroad" , "St. James Place" , "Community Chest" , "Tennessee Avenue" , "New York Avenue" , "Free Parking" , "Kentucky Avenue" , "Chance" , "Indiana Avenue" , "Illinois Avenue" , "B & O Railroad" , "Atlantic Avenue" , "Ventnor Avenue" , "Water Works" , "Marvin Gardens" , "Go to jail" , "Pacific Avenue" , "North Carolina Avenue" , "Community Chest" , "Pennsylvania Avenue" , "Short Line Railroad" , "Chance" , "Park Place" , "Luxury Tax" , "Boardwalk"))

chanceDeck<-data.frame(index = 1:15, card = c("Advance to Go", "Advance to Illinois Ave.", "Advance to St. Charles Place", "Advance token to nearest Utility", " Advance token to the nearest Railroad","Take a ride on the Reading Railroad", "Take a walk on the Boardwalk","Go to Jail", "Go Back 3 Spaces", "Bank pays you dividend of $50", "Get out of Jail Free", "Make general repairs on all your property", "Pay Poor Tax of $15","You have been Elected Chairman of the Board", "You inherit $100"))

communityDeck<- data.frame(index=1:16, card = c("Advance to Go", "Go to Jail","Bank error in your favor. Collect $200", "Doctor's fees Pay $50", "From sale of stock you get $45", "Get out of Jail Free", "Grand opera Night Opening", "Christmas Fund matures","Income tax refund","Life insurance matures. Collect $100","Pay hospital fess of $100", "Pay school tax of $150","Receive for services $25", "You are assesed for street repairs", "You ave won second prize in a beauty contest", "You inherit $100"))
```

```{r player}
player1<- "Player 1"
player2<- "Player 2"
player3<- "Player 3"
players <- c(player1, player2, player3)
```

```{r}

```