---
title: "Final_q4"
author: "Amber Duevel"
date: "4/26/2022"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r dice}
check_double<-function(face, double_count){
  movement=0
  if(face[1]==face[2]){
    movement=movement+sum(face)
    double_count=double_count+1
    dice()
    print("rolled doubles")
      if(double_count==3){
        player_df[player+1, 2] = 11
        print("go to jail")
        return(assign("player_df",player_df,.GlobalEnv))
      }else{
        movement=movement+sum(face)
      }
  }else{
    movement=movement+sum(face)
  }
}
jail_out<-function(face, jail_count){
  if(face[1]==face[2]){
    movement=sum(face)
  }else{
    jail_count=jail_count+1
    if(jail_count==3){
      movement=sum(face)
    }
    return(jail_count)
  }
}
dice <- function(movement){
  double_count = 0
  jail_count = 0
  face = sample(1:6,2,replace=TRUE)
  if(player_df[player+1, 2] == 11){
    while(jail_count<3){
      jail_out(face, jail_count)
      break
    }
  }
  if(double_count<=3){
    check_double(face, double_count)
  }
}
```

```{r}
library(dplyr)
cc_cards = data.frame()
cc1 = c("Advance to Go(collect $200)", 200, TRUE, "Go")
cc2 = c("Bank error in your favor. Collect $200", 200, FALSE, NA)
cc3 = c("Doctor's fee. Pay $50", -50, FALSE, NA)
cc4 = c("From sale of stock you get $50", 50, FALSE, NA)
cc5 = c("Get out of jail free", 0, FALSE, NA)
cc6 = c("Go to jail. Go directly to jail, do not pass Go, do not collect $200", 0, TRUE, "Just Visiting")
cc7 = c("Holiday fund matures. Receive $100", 100, FALSE, NA)
cc8 = c("Income tax refund. Collect $20", 20, FALSE, NA)
cc9 = c("It is your birthday. Collect $10 from every player", 0, FALSE, NA)
cc10 = c("Life insurance matures. Collect $100", 100, FALSE, NA)
cc11 = c("Pay hospital fees of $100", -100, FALSE, NA)
cc12 = c("Pay school fees of $50", -50, FALSE, NA)
cc13 = c("Receive $25 consultancy fee", -25, FALSE, NA)
cc14 = c("You are assessed for street repair. $40 per house. $115 per hotel", 0, FALSE, NA)
cc15 = c("You have won second prize in a beauty contest. Collect $10", 10, FALSE, NA)
cc16 = c("You inherit $100", 100, FALSE, NA)
cc_cards <- rbind(cc_cards, cc1, cc2, cc3, cc4, cc5, cc6, cc7, cc8, cc9, cc10, cc11, cc12, cc13, cc14, cc15, cc16)
colnames(cc_cards) = c("Card Description")
cc_cards_vec <- c("Advance to Go(collect $200)", "Bank error in your favor. Collect $200", "Doctor's fee. Pay $50", "From sale of stock you get $50", "Get out of jail free", "Go to jail. Go directly to jail, do not pass Go, do not collect $200", "Holiday fund matures. Receive $100", "Income tax refund. Collect $20", "It is your birthday. Collect $10 from every player", "Life insurance matures. Collect $100", "Pay hospital fees of $100", "Pay school fees of $50", "Receive $25 consultancy fee", "You are assessed for street repair. $40 per house. $115 per hotel", "You have won second prize in a beauty contest. Collect $10", "You inherit $100")
jail_cc = function() {
  r <- sample(cc_cards_vec, size = 1, replace = FALSE)
  cat("CC...", r)
  space = player_df[player+1, 2]
  if (r == "Go to jail. Go directly to jail, do not pass Go, do not collect $200") {
    space = 11
    }
    else if(r == "Advance to Go(collect $200)") {
      space = 1
    }else{
      space=space
    }
  assign("player_df",player_df,.GlobalEnv)
  return(space) 
}
chance_cards = data.frame()
c1 = c("Advance to Boardwalk", 0, TRUE, "Boardwalk")
c2 = c("Advance to Go(collect $200)", 200, TRUE, "Go")
c3 = c("Advance to Illinois Avenue. If you pass Go, collect $200", 0, TRUE, "Illinois Avenue")
c4 = c("Advance to St. Charles Place. If you pass Go, collect $200", 0, TRUE, "St. Charles Place")
c5 = c("Advance to the nearest Railroad. If unowned, you may buy it from the Bank. If owned, pay owner twice the rental to which they are otherwise entitled", 0, TRUE, "Railroad") #Needs to look for the nearest railroad, which it's not doing right now
c6 = c("Advance to the nearest Railroad. If unowned, you may buy it from the Bank. If owned, pay owner twice the rental to which they are otherwise entitled", 0, TRUE, "Railroad") #Same as the previous one
c7 = c("Advance token to the nearest Utility. If unowned, you may buy it from the Bank. If owned, throw dice and pay owner a total ten times amount thrown.", 0, TRUE, "Utility") #Same as the previous one but with utilities
c8 = c("Bank pays you dividend of $50", 50, FALSE, NA)
c9 = c("Get out of jail free", 0, FALSE, NA)
c10 = c("Go back 3 spaces", 0, TRUE, "Current space minus 3")
c11 = c("Go to jail. Go directly to jail, do not pass Go, do not collect $200", 0, TRUE, "Just Visiting")
c12 = c("Make general repairs on all your property. For each house pay $25. For each hotel pay $100", 0, FALSE, NA)
c13 = c("Speeding fine $15", -15, FALSE, NA)
c14 = c("Take a trip to Reading Railroad. If you pass Go, collect $200", 0, TRUE, "Go")
c15 = c("You have been elected Chairman of the Board. Pay each player $50", -50, FALSE, NA)
c16 = c("Your building loan matures. Collect $150", 150, FALSE, NA)
chance_cards = rbind(chance_cards, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16)
colnames(chance_cards) = c("Card Description")
chance_cards_vec <- c("Advance to Boardwalk", "Advance to Go(collect $200)", "Advance to Illinois Avenue. If you pass Go, collect $200", "Advance to St. Charles Place. If you pass Go, collect $200", "Advance to the nearest Railroad. If unowned, you may buy it from the Bank. If owned, pay owner twice the rental to which they are otherwise entitled", "Advance to the nearest Railroad. If unowned, you may buy it from the Bank. If owned, pay owner twice the rental to which they are otherwise entitled", "Advance token to the nearest Utility. If unowned, you may buy it from the Bank. If owned, throw dice and pay owner a total ten times amount thrown.", "Bank pays you dividend of $50", "Get out of jail free", "Go back 3 spaces", "Go to jail. Go directly to jail, do not pass Go, do not collect $200", "Make general repairs on all your property. For each house pay $25. For each hotel pay $100", "Speeding fine $15", "Take a trip to Reading Railroad. If you pass Go, collect $200", "You have been elected Chairman of the Board. Pay each player $50", "Your building loan matures. Collect $150")
jail_c = function() {
  r1 <- sample(chance_cards_vec, size = 1, replace = FALSE)
  cat("C...", r1)
  space = player_df[player+1, 2]
  if (r1 == "Go to jail. Go directly to jail, do not pass Go, do not collect $200") {
    space = 11
    }
    else if (r1 == "Advance to Boardwalk") {
      space = 40
    }
    else if (r1 == "Advance to Go(collect $200)") {
      space = 1
    }
    else if (r1 == "Advance to Illinois Avenue. If you pass Go, collect $200") {
      space = 25
    }
    else if (r1 == "Advance to St. Charles Place. If you pass Go, collect $200") {
      space = 12
    }
    else if (r1 == "Advance to the nearest Railroad. If unowned, you may buy it from the Bank. If owned, pay owner twice the rental to which they are otherwise entitled") {
      if (space > 1 && space < 6) {
        space = 6
      }
      else if (space < 16 && space > 6) {
        space = 16
      }
      else if (space < 26 && space > 16) {
        space = 26
      }
      else {
        space = 36
      }
    }
    else if (r1 == "Advance token to the nearest Utility. If unowned, you may buy it from the Bank. If owned, throw dice and pay owner a total ten times amount thrown.") {
      if (space > 1 && space < 13) {
        space = 13
      }
      else if (space < 29 && space > 13) {
        space = 29
      }
      else {
        space = 13
      }
    }
    else if (r1 == "Go back 3 spaces") {
      space = space - 3
      if(space<1){
        space=space+40
      }
    }
    else if (r1 == "Take a trip to Reading Railroad. If you pass Go, collect $200") {
      space = 6
    }
    else {
      space=space
    }
  assign("player_df",player_df,.GlobalEnv)
  return(space)
}
```




```{r board}
mono_board = data.frame()
# All of the spaces on the board
go = c("Go", 0, 200, 0, "None")
mediterranean = c("Mediterranean Avenue", 0, 172, 0, "Purple")
community1 = c("Community Chest1", 0, 155, 0, "Cards")
baltic = c("Baltic Avenue", 0, 136, 0, "Purple")
income = c("Income Tax", 0, 118, 0, "None")
reading = c("Reading Railroad", 0, 100, 0, "Railroad")
oriental = c("Oriental Avenue", 0, 82, 0, "Light Blue")
chance1 = c("Chance1", 0, 64, 0, "Cards")
vermont = c("Vermont Avenue", 0, 46, 0, "Light Blue")
connecticut = c("Connecticut Avenue", 0, 28, 0, "Light Blue")
just_visiting_jail = c("Just Visiting/Jail", 0, 0, 0, "None")
charles = c("St. Charles Place", 0, 0, 28, "Pink")
electric = c("Electric Company", 0, 0, 46, "Utilities")
states = c("States Avenue", 0, 0, 64, "Pink")
virginia = c("Virginia Avenue", 0, 0, 82, "Pink")
penn_railroad = c("Pennsylvania Railroad", 0, 0, 100, "Railroad")
james = c("St. James Place", 0, 0, 118, "Orange")
community2 = c("Community Chest2", 0, 0, 136, "Cards")
tennessee = c("Tennessee Avenue", 0, 0, 154, "Orange")
new_york = c("New York Avenue", 0, 0, 172, "Orange")
parking = c("Free Parking", 0, 0, 200, "None")
kentucky = c("Kentucky Avenue", 0, 28, 200, "Red")
chance2 = c("Chance2", 0, 46, 200, "Cards")
indiana = c("Indiana Avenue", 0, 64, 200, "Red")
illinois = c("Illinois Avenue", 0, 82, 200, "Red")
b_o = c("B&O Railroad", 0, 100, 200, "Railroad")
atlantic = c("Atlantic Avenue", 0, 118, 200, "Yellow")
ventnor = c("Ventnor Avenue", 0, 136, 200, "Yellow")
water = c("Water Works", 0, 155, 200, "Utilities")
marvin = c("Marvin Gardens", 0, 172, 200, "Yellow")
jail = c("Go to Jail", 0, 200, 200, "None")
pacific = c("Pacific Avenue", 0, 200, 172, "Green")
carolina = c("North Carolina Avenue", 0, 200, 154, "Green")
community3 = c("Community Chest3", 0, 200, 136, "Cards")
penn_avenue = c("Pennsylvania Avenue", 0, 200, 118, "Green")
short = c("Short Line", 0, 200, 100, "Railroad")
chance3 = c("Chance3", 0, 200, 82, "Cards")
park = c("Park Place", 0, 200, 64, "Dark Blue")
luxury = c("Luxury Tax", 0, 200, 46, "None")
boardwalk = c("Boardwalk", 0, 200, 28, "Dark Blue")
mono_board = rbind(mono_board, go, mediterranean, community1, baltic, income, reading, oriental, chance1, vermont, connecticut, just_visiting_jail, charles, electric, states, virginia, penn_railroad, james, community2, tennessee, new_york, parking, kentucky, chance2, indiana, illinois, b_o, atlantic, ventnor, water, marvin, jail, pacific, carolina, community3, penn_avenue, short, chance3, park, luxury, boardwalk)
colnames(mono_board) = c('space_name', 'count', 'x_dimension', 'y_dimension', 'space_color')
```

```{r}
mono_board = transform(mono_board, x_dimension = as.numeric(x_dimension))
mono_board = transform(mono_board, y_dimension = as.numeric(y_dimension))
mono_board = transform(mono_board, count = as.numeric(count))
```


```{r turn}
player_df = data.frame()
player1 = c("player1", 1, 1500)
player2 = c("player2", 1, 1500)
player3 = c("player3", 1, 1500)
player4 = c("player4", 1, 1500)
player_df = rbind(player_df, player1, player2, player3, player4)
colnames(player_df) = c("name", "position", "money")
player_df = transform(player_df, position = as.numeric(position))
num_players = nrow(player_df)
#Columns: player, x-coordinate, y-coordinate
mono_graph_data = data.frame()
mono_graph_data = rbind(c(player_df[1, 1], mono_board[player_df[1, 2], 3], mono_board[player_df[1, 2], 4]), 
                        c(player_df[2, 1], mono_board[player_df[2, 2], 3], mono_board[player_df[2, 2], 4]), 
                        c(player_df[3, 1], mono_board[player_df[3, 2], 3], mono_board[player_df[3, 2], 4]), 
                        c(player_df[4, 1], mono_board[player_df[4, 2], 3], mono_board[player_df[4, 2], 4]))
colnames(mono_graph_data) = c('player', 'x_coordinate', 'y_coordinate')
rounds = 0
player = 0
move = function() {
  roll = dice()
  space = player_df[player+1, 2] + roll
  if (space == 40) {
    space = 40
  }
  else {
    space = space%%40
  }
  if(space==3 || space==18 || space==34){
    space=jail_cc()
  }else if(space==8 || space==23 || space==37){
    space=jail_c()
  }
  return(space)
}
player_turn = function(player) {
  s = move()
  mono_board[s, 2] = as.numeric(mono_board[s, 2] + 1)
  player_df[player+1, 2] = s
  
  mono_graph_data = rbind(mono_graph_data, c(player_df[player+1, 1], mono_board[player_df[player+1, 2], 3], mono_board[player_df[player+1, 2], 4]))
  
  return(c(assign("mono_board", mono_board, .GlobalEnv), assign("player_df", player_df, .GlobalEnv), assign("mono_graph_data", mono_graph_data, .GlobalEnv)))
}
while (rounds < 500) {
  player_turn(player)
  player = (player+1)%%num_players
  rounds = rounds + 1
}
#Won't count the card spaces when playing so the count is zero. 
```



```{r image}
library(grid)
library(jpeg)
library(tidyverse)
library(ggplot2)
library(gganimate)
Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)
board_img = rasterGrob(readJPEG("monopolyboard.jpg"), 
                       width = unit(1, "npc"), height = unit(1, "npc"))
```

```{r plot}
mono_graph_data = transform(mono_graph_data, x_coordinate = as.numeric(x_coordinate))
mono_graph_data = transform(mono_graph_data, y_coordinate = as.numeric(y_coordinate))
mono_graph = ggplot(mono_graph_data, group = "player") +
  annotation_custom(board_img) +
  theme(aspect.ratio = 1) +
  scale_x_continuous(limits = c(0, 200)) +
  scale_y_continuous(limits = c(0, 200)) +
  geom_point(aes(x = x_coordinate, y = y_coordinate, color = player, size = 5))
mono_graph
```

```{r count}
#Again, not sure if someone already made a graph showing the counts, but if not, we can use mine from question 2
count_plot = ggplot(mono_board, aes(x = space_name, y = count), group = "space_color") +
  geom_bar(stat = "identity", aes(fill = space_color)) +
  coord_flip() +
  ggtitle("Count for Each Space") +
  ylab("Count") +
  xlab("Space Name") +
  labs(fill = "Type of Space")
count_plot
```
