---
title: "Final_q5"
author: "Amber Duevel"
date: "4/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r dice}
check_double<-function(){
  if(face[1]==face[2]){
    movement=sum(face)
    dice()
    double_count=double_count+1
      if(double_count==3){
        player_df[player+1, 2] = 11
        return(assign("player_df",player_df,.GlobalEnv))
      }
    return(double_count)
  }else{
    movement=sum(face)
  }
}

jail_out<-function(){
  if(face[1]==face[2]){
    movement=sum(face)
  }else{
    jail_count=jail_count+1
    if(jail_count==3){
      movement=sum(face)
    }
    return(jail_count)
  }
}

dice <- function(){
  double_count = 0
  jail_count = 0
  face = sample(1:6,2,replace=TRUE)
  if(player_df[player+1, 2] = 11){
    while(jail_count<3){
    jail_out()
    break
    }
  }
  while(double_count<3){
    check_double()
  }
}
```

```{r Money}
money_board<-function(){
  if(player_df[player+1, 2] = 24 || player_df[player+1, 2] = 39){
    cc_money()
  }
  if(player_df[player+1, 2] = 19 || player_df[player+1, 2] = 34 ){
    chance_money()
  }
  if(player_df[player+1, 2] = 21){
    free_parking()
  }
}

cc_money<-function(){
  money_amount = money_amount + cc_cards[,2]
  if(cc_cards[,2]<0){
    bank_money = bank_money - cc_cards[,2]
    return(bank_money)
  }
}

chance_money<-function(){
  money_amount = money_amount + chance_cards[,2]
  if(chance_cards[,2]<0){
    bank_money = bank_money - chance_cards[,2]
  }
}

free_parking<-function(){
  if(parking_money==0){
    money_amout=money_amout+100
    return(money_amout)
  }
  parking_money = parking_money + bank_money
  money_amount = money_amount + parking_money
}
```

```{r board}
mono_board = data.frame()

# All of the spaces on the board
go = c("Go", 0, 200, 0, "None")
mediterranean = c("Mediterranean Avenue", 0, 172, 0, "Purple")
community1 = c("Community Chest1", 0, 155, 0, "Cards")
baltic = c("Baltic Avenue", 0, 136, 0, "Purple")
income = c("Income Tax", 0, 118, 0, "None")
reading = c("Reading Railroad", 0, 100, 0, "Railroad")
oriental = c("Oriental Avenue", 0, 82, 0, "Light Blue")
chance1 = c("Chance1", 0, 64, 0, "Cards")
vermont = c("Vermont Avenue", 0, 46, 0, "Light Blue")
connecticut = c("Connecticut Avenue", 0, 28, 0, "Light Blue")
just_visiting_jail = c("Just Visiting/Jail", 0, 0, 0, "None")
charles = c("St. Charles Place", 0, 0, 28, "Pink")
electric = c("Electric Company", 0, 0, 46, "Utilities")
states = c("States Avenue", 0, 0, 64, "Pink")
virginia = c("Virginia Avenue", 0, 0, 82, "Pink")
penn_railroad = c("Pennsylvania Railroad", 0, 0, 100, "Railroad")
james = c("St. James Place", 0, 0, 118, "Orange")
community2 = c("Community Chest2", 0, 0, 136, "Cards")
tennessee = c("Tennessee Avenue", 0, 0, 154, "Orange")
new_york = c("New York Avenue", 0, 0, 172, "Orange")
parking = c("Free Parking", 0, 0, 200, "None")
kentucky = c("Kentucky Avenue", 0, 28, 200, "Red")
chance2 = c("Chance2", 0, 46, 200, "Cards")
indiana = c("Indiana Avenue", 0, 64, 200, "Red")
illinois = c("Illinois Avenue", 0, 82, 200, "Red")
b_o = c("B&O Railroad", 0, 100, 200, "Railroad")
atlantic = c("Atlantic Avenue", 0, 118, 200, "Yellow")
ventnor = c("Ventnor Avenue", 0, 136, 200, "Yellow")
water = c("Water Works", 0, 155, 200, "Utilities")
marvin = c("Marvin Gardens", 0, 172, 200, "Yellow")
jail = c("Go to Jail", 0, 200, 200, "None")
pacific = c("Pacific Avenue", 0, 200, 172, "Green")
carolina = c("North Carolina Avenue", 0, 200, 154, "Green")
community3 = c("Community Chest3", 0, 200, 136, "Cards")
penn_avenue = c("Pennsylvania Avenue", 0, 200, 118, "Green")
short = c("Short Line", 0, 200, 100, "Railroad")
chance3 = c("Chance3", 0, 200, 82, "Cards")
park = c("Park Place", 0, 200, 64, "Dark Blue")
luxury = c("Luxury Tax", 0, 200, 46, "None")
boardwalk = c("Boardwalk", 0, 200, 28, "Dark Blue")

mono_board = rbind(mono_board, go, mediterranean, community1, baltic, income, reading, oriental, chance1, vermont, connecticut, just_visiting_jail, charles, electric, states, virginia, penn_railroad, james, community2, tennessee, new_york, parking, kentucky, chance2, indiana, illinois, b_o, atlantic, ventnor, water, marvin, jail, pacific, carolina, community3, penn_avenue, short, chance3, park, luxury, boardwalk)

colnames(mono_board) = c('space_name', 'count', 'x_dimension', 'y_dimension', 'space_color')
```

```{r}
mono_board = transform(mono_board, x_dimension = as.numeric(x_dimension))
mono_board = transform(mono_board, y_dimension = as.numeric(y_dimension))
mono_board = transform(mono_board, count = as.numeric(count))
```

```{r turn}
player_df = data.frame()
player1 = c("player1", 1, 1500)
player2 = c("player2", 1, 1500)
player3 = c("player3", 1, 1500)
player4 = c("player4", 1, 1500)
player_df = rbind(player_df, player1, player2, player3, player4)
colnames(player_df) = c("name", "position", "money")
player_df = transform(player_df, position = as.numeric(position))
num_players = nrow(player_df)

#Columns: player, x-coordinate, y-coordinate
mono_graph_data = data.frame()
mono_graph_data = rbind(c(player_df[1, 1], mono_board[player_df[1, 2], 3], mono_board[player_df[1, 2], 4]), 
                        c(player_df[2, 1], mono_board[player_df[2, 2], 3], mono_board[player_df[2, 2], 4]), 
                        c(player_df[3, 1], mono_board[player_df[3, 2], 3], mono_board[player_df[3, 2], 4]), 
                        c(player_df[4, 1], mono_board[player_df[4, 2], 3], mono_board[player_df[4, 2], 4]))
colnames(mono_graph_data) = c('player', 'x_coordinate', 'y_coordinate')

rounds = 0
player = 0

move = function() {
  roll = dice_simple()
  space = player_df[player+1, 2] + roll
  if (space == 40) {
    space = 40
  }
  else {
    space = space%%40
  }
  return(space)
}

player_turn = function(player) {
  s = move()
  mono_board[s, 2] = as.numeric(mono_board[s, 2] + 1)
  player_df[player+1, 2] = s
  
  mono_graph_data = rbind(mono_graph_data, c(player_df[player+1, 1], mono_board[player_df[player+1, 2], 3], mono_board[player_df[player+1, 2], 4]))
  
  return(c(assign("mono_board", mono_board, .GlobalEnv), assign("player_df", player_df, .GlobalEnv), assign("mono_graph_data", mono_graph_data, .GlobalEnv)))
}

while (rounds < 100) {
  player_turn(player)
  player = (player+1)%%num_players
  rounds = rounds + 1
}
```

```{r image}
library(grid)
library(jpeg)
library(tidyverse)
library(ggplot2)
library(gganimate)
Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)

board_img = rasterGrob(readJPEG("monopolyboard.jpg"), 
                       width = unit(1, "npc"), height = unit(1, "npc"))
```

```{r plot}
mono_graph_data = transform(mono_graph_data, x_coordinate = as.numeric(x_coordinate))
mono_graph_data = transform(mono_graph_data, y_coordinate = as.numeric(y_coordinate))

mono_graph = ggplot(mono_graph_data, group = "player") +
  annotation_custom(board_img) +
  theme(aspect.ratio = 1) +
  scale_x_continuous(limits = c(0, 200)) +
  scale_y_continuous(limits = c(0, 200)) +
  geom_point(aes(x = x_coordinate, y = y_coordinate, color = player, size = 5))
mono_graph
```

```{r count}
count_plot = ggplot(mono_board, aes(x = space_name, y = count), group = "space_color") +
  geom_bar(stat = "identity", aes(fill = space_color)) +
  coord_flip() +
  ggtitle("Count for Each Space") +
  ylab("Count") +
  xlab("Space Name") +
  labs(fill = "Type of Space")
count_plot
```
